/**
 * ai-provider.ts
 *
 * Centralised AI provider helper for Talkify.
 *
 * Strategy:
 *   1. Try Gemini (primary).
 *   2. If Gemini returns 429 / quota / rate-limit error → fall back to OpenRouter.
 *   3. If OpenRouter key is absent, Gemini continues working normally.
 *   4. If both fail, throw so the caller can use its existing error handling.
 *
 * Never log secrets or user content.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface GeminiContent {
  role: "user" | "model";
  parts: { text: string }[];
}

export interface GeminiRequest {
  contents: GeminiContent[];
  systemInstruction?: { parts: { text: string }[] };
  generationConfig?: Record<string, unknown>;
}

export interface AIResponse {
  /** The raw text generated by whichever provider succeeded. */
  text: string;
  /** Which provider actually produced the response. */
  provider: "gemini" | "openrouter";
}

// ─── Constants ────────────────────────────────────────────────────────────────

const GEMINI_BASE =
  "https://generativelanguage.googleapis.com/v1beta/models";

const OPENROUTER_BASE = "https://openrouter.ai/api/v1/chat/completions";

/**
 * HTTP status codes / text patterns that indicate the Gemini quota/rate-limit
 * was exhausted and we should try OpenRouter instead.
 */
const SHOULD_FALLBACK_STATUSES = new Set([429, 503]);

// ─── Helpers ─────────────────────────────────────────────────────────────────

function shouldFallback(status: number, bodyText: string): boolean {
  if (SHOULD_FALLBACK_STATUSES.has(status)) return true;
  const lower = bodyText.toLowerCase();
  // Gemini surfaces quota errors as 400 with specific messages
  return (
    status === 400 &&
    (lower.includes("quota") ||
      lower.includes("rate limit") ||
      lower.includes("resource_exhausted"))
  );
}

// ─── Gemini call ─────────────────────────────────────────────────────────────

async function callGemini(
  model: string,
  apiKey: string,
  body: GeminiRequest
): Promise<string> {
  const url = `${GEMINI_BASE}/${model}:generateContent?key=${apiKey}`;

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const raw = await res.text();
    const err = new GeminiError(res.status, raw);
    throw err;
  }

  const data = await res.json();
  const text: string =
    data?.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
  if (!text) throw new Error("Gemini returned an empty response.");
  return text.trim();
}

class GeminiError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: string
  ) {
    super(`Gemini HTTP ${status}`);
    this.name = "GeminiError";
  }
}

// ─── OpenRouter call ──────────────────────────────────────────────────────────

/**
 * Converts a Gemini-format request into an OpenAI-compatible chat request
 * and calls OpenRouter.
 */
async function callOpenRouter(
  geminiBody: GeminiRequest,
  apiKey: string,
  model: string
): Promise<string> {
  // Build OpenAI-style messages from Gemini contents
  const messages: { role: "system" | "user" | "assistant"; content: string }[] =
    [];

  // Inject system prompt if present
  const systemText =
    geminiBody.systemInstruction?.parts?.map((p) => p.text).join("\n") ?? "";
  if (systemText) {
    messages.push({ role: "system", content: systemText });
  }

  for (const c of geminiBody.contents) {
    const role = c.role === "model" ? "assistant" : "user";
    const content = c.parts.map((p) => p.text).join("\n");
    messages.push({ role, content });
  }

  const res = await fetch(OPENROUTER_BASE, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
      "HTTP-Referer": "https://talkify.app",
      "X-Title": "Talkify",
    },
    body: JSON.stringify({
      model,
      messages,
      temperature: (geminiBody.generationConfig?.temperature as number) ?? 0.7,
      max_tokens:
        (geminiBody.generationConfig?.maxOutputTokens as number) ?? 800,
      ...(geminiBody.generationConfig?.responseMimeType === "application/json" 
          ? { response_format: { type: "json_object" } } 
          : {})
    }),
  });

  if (!res.ok) {
    const raw = await res.text();
    throw new Error(`OpenRouter HTTP ${res.status}: ${raw.slice(0, 200)}`);
  }

  const data = await res.json();
  const text: string =
    data?.choices?.[0]?.message?.content ?? "";
  
  if (!text) {
    console.error("OpenRouter raw empty response:", JSON.stringify(data));
    throw new Error("OpenRouter returned an empty response.");
  }
  return text.trim();
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Calls Gemini first.  If Gemini hits a quota/rate-limit error **and**
 * OPENROUTER_API_KEY is configured, transparently falls back to OpenRouter.
 *
 * @param geminiModel  e.g. "gemini-flash-latest"
 * @param body         Gemini-format request body
 */
export async function generateWithFallback(
  geminiModel: string,
  body: GeminiRequest
): Promise<AIResponse> {
  const geminiKey =
    process.env.GEMINI_API_KEY ??
    process.env.NEXT_PUBLIC_GEMINI_API_KEY ??
    "";
  const openrouterKey = process.env.OPENROUTER_API_KEY ?? "";
  const openrouterModel = process.env.OPENROUTER_MODEL ?? "";

  // ── 1. Try Gemini ─────────────────────────────────────────────────────────
  if (geminiKey) {
    try {
      const text = await callGemini(geminiModel, geminiKey, body);
      return { text, provider: "gemini" };
    } catch (err) {
      if (err instanceof GeminiError && shouldFallback(err.status, err.body)) {
        // Log without secrets
        console.warn(
          `[AI] Gemini quota/rate-limit (HTTP ${err.status}) → falling back to OpenRouter`
        );
        // Fall through to OpenRouter below
      } else {
        // Non-quota Gemini error — rethrow immediately, no fallback
        throw err;
      }
    }
  }

  // ── 2. Try OpenRouter ─────────────────────────────────────────────────────
  if (openrouterKey && openrouterModel) {
    try {
      const text = await callOpenRouter(body, openrouterKey, openrouterModel);
      console.info("[AI] OpenRouter fallback succeeded.");
      return { text, provider: "openrouter" };
    } catch (err) {
      console.error("[AI] OpenRouter fallback also failed:", (err as Error).message);
      throw err;
    }
  }

  // ── 3. Both unavailable ───────────────────────────────────────────────────
  if (!geminiKey) {
    throw new Error("No AI provider configured. Set GEMINI_API_KEY.");
  }
  // Gemini failed with quota but no OpenRouter configured
  throw new Error(
    "Gemini quota exhausted and OPENROUTER_API_KEY / OPENROUTER_MODEL are not configured."
  );
}
